homographies:
    translation: true
    rotation: true
    scaling: true
    perspective: true
    scaling_amplitude: 0.2
    perspective_amplitude_x: 0.1
    perspective_amplitude_y: 0.1
    patch_ratio: 0.9
    max_angle: 0.3925 # pi/8
preprocessing:
    resize: [240, 320]
