data:
    name: 'one_image_icip_three'
    cache_in_memory: true
    validation_size: 1
    labels: ../outputs/chain_one_image_icip_three/mp_trained_export
    augmentation:
        photometric:
            enable: true
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur']
            params:
                random_brightness: {max_abs_change: 50}
                random_contrast: {strength_range: [0.5, 1.5]}
                additive_gaussian_noise: {stddev_range: [0, 10]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.5]
                    kernel_size_range: [100, 150]
                motion_blur: {max_kernel_size: 3}
        homographic:
            enable: false  # not implemented
    warped_pair:
        enable: true
        params:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.2
            perspective_amplitude_x: 0.05
            perspective_amplitude_y: 0.05
            patch_ratio: 0.95
            max_angle: 1.57
            allow_artifacts: false
        valid_border_margin: 3
model:
    name: 'super_point'
    batch_size: 1
    eval_batch_size: 1
    learning_rate: 0.0001
    lambda_d: 800
    positive_margin: 1
    negative_margin: 0.2
    lambda_loss: 1
    detection_threshold: 0.001
    nms: 4
    top_k: 600
train_iter: 17000000
validation_interval: 50000
save_interval: 5000
keep_checkpoints: 5
